controllers:
    resource: ../src/Controller/
    type: annotation

#controllers_main:
#    resource: ../src/Controller/
#    type: annotation
#    prefix: /{_locale}
#    requirements:
#        _locale: '%app_locales%'
#    default:
#        _locale: '%locale%'

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
        path: '/%locale%'
        permament: true